### ISSUE TITLE
Chord spec for meta

### ISSUE THREAD

**Issue by pdh** [pdh/meltodies#15]
Thinking something like this

```
Am:
  e: 0
  B: 1
  G: 2
  D: 2
  A: 0
  E: x
```
